Debug host key generation

diff --git a/bin/entrypoint b/bin/entrypoint
--- a/bin/entrypoint
+++ b/bin/entrypoint
@@ -27,10 +27,10 @@ test ! -w "$_home"/.ssh && echo "WARNING: '$_home/.ssh' is not writeable" || {
   dir_not_empty "$SSH_CONFIG_VOLUME" && {
     echo "Copying SSH files: '$SSH_CONFIG_VOLUME' -> '$_home/.ssh'..."
     ls -lhFa "$_home"/.ssh && touch "$_home"/.ssh/environment && \
-    cp -av "$SSH_CONFIG_VOLUME"/* "$_home"/.ssh && \
-    ls -lhFa "$_home"/.ssh || return
+    cp -av "$SSH_CONFIG_VOLUME"/* "$_home"/.ssh || return
   }
   chown -R $_USER:$_USER "$_home"/.ssh && chmod -R 600 "$_home"/.ssh && chmod 700 "$_home"/.ssh
+  ls -lhFa "$_home"/.ssh || return
 }
 
 _file="$_home"/.ssh/authorized_keys
@@ -45,14 +45,14 @@ setup_env_vars
 
 # Copy default config from cache
 dir_not_empty /etc/ssh || {
-  test -d /etc/ssh && \
-  echo "/etc/ssh is empty." && \
-  dir_not_empty /etc/ssh.cache && cp -av /etc/ssh.cache/* /etc/ssh/
+  test -d /etc/ssh && echo "/etc/ssh is empty." || echo "/etc/ssh is not a dir"
+  test -d /etc/ssh && dir_not_empty /etc/ssh.cache && cp -av /etc/ssh.cache/* /etc/ssh/
 }
 
 # Generate Host keys, if required
-dir_not_empty /etc/ssh/ssh_host_* || {
-  which ssh-keygen >/dev/null 2>&1 && ssh-keygen -A
+dir_not_empty /etc/ssh/ssh_host_* && echo "Host keys present." || {
+  echo "Generating host keys..."
+  which ssh-keygen >/dev/null 2>&1 && ssh-keygen -A || echo "'ssh-keygen' missing."
 }
 
 # Allow running SSHD as non-root user
